---
- name: "move backend files to server."
  copy:
    src: /root/project/backend
    dest: /home/ubuntu
    recursive: true

- name: "install node dependencies"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: "build backend"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: "run migrations again"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations

- name: "start backend"
  become: true
  shell: |
    cd /home/ubuntu/backend    
    pm2 start npm -- run start